### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by markhulia** [haaris272k/Rapid-inputs#1]
Cool idea, but the game is missing `requirements.txt` with `inputimeout` listed in it

**Comment by markhulia** [comment]
@haaris272k Saw your post on linkedin and decided to give it a try

**Comment by haaris272k** [comment]
Sure sir, thanks for pointing it out.
Could u pls suggest me what could I add in requirements.txt for this
project and then generally what all should be added. I am asking this coz I
am new tk GitHub. Any suggestion would be appreciated.

Thank you.

**Comment by haaris272k** [comment]
Thanx for pointing it out. I would surely add it.
